### ISSUE TITLE
Refactor the code

### ISSUE THREAD

**Issue by syjer** [digitalfondue/jscoverproxy-maven-plugin#4]
As it's quite ugly :)

**Comment by tntim96** [comment]
There's some code in [JSCoverMojoBase](https://github.com/tntim96/JSCover-maven-plugin/blob/master/plugin-parent/common/src/main/java/jscover/maven/JSCoverMojoBase.java) and [ServerMojo](https://github.com/tntim96/JSCover-maven-plugin/blob/master/plugin-parent/server/src/main/java/jscover/maven/ServerMojo.java) which could probably be used.
