### ISSUE TITLE
Upgrade to JSCover 2.x

### ISSUE THREAD

**Issue by BBE78** [digitalfondue/jscoverproxy-maven-plugin#7]
JSCover has released [2.0.1 version](https://github.com/tntim96/JSCover/releases/tag/v2.0.1) few days ago: upgrade the plugin to use this new major version

**Comment by syjer** [comment]
Hi @BBE78 , thank you for the head up, I'll do the update as soon as possible (Ideally this afternoon)

**Comment by tntim96** [comment]
It may not be a trivial upgrade to due to different guava dependencies. See how you go.

**Comment by syjer** [comment]
@tntim96 yep, you are right, the guava dependency seems to cause some classloader issue (missing classes).

I'll dig deeper if I can find a decent solution.

**Comment by syjer** [comment]
version 2.0.1 is up on maven central: http://central.maven.org/maven2/ch/digitalfondue/jscover/jscoverproxy-maven-plugin/2.0.1/ . I've tested on my test application (https://github.com/syjer/spring-ng-webjar) and it seems to work :)
